### ISSUE TITLE
Vreemde melding

### ISSUE THREAD

**Issue by PvdGulik** [altrnate32/esp-lg-control#10]
Goedenavond,

Sinds lange tijd weereens in log gekeken van Esphome in Home assisatant.
Daarin zie ik nu steeds deze melding terugkomen, verder lijkt het wel goed te werken (ook al is het zomer ;-)

`[20:26:05][D][modbus:119]: Modbus error function code: 0x84 exception: 2
[20:26:05][E][modbus_controller:068]: Modbus error function code: 0x4 exception: 2 
[20:26:05][E][modbus_controller:077]: Modbus error - last command: function code=0x4  register address = 0xB  registers count=20 payload size=0`

Ik zie daarnaast in HomeAssistant dat de “ SWW Temperatuur” niet meer beschikbaar is… 

Vreemd toch?

Dank!

**Comment by altrnate32** [comment]
Wat raar. Ik heb niet genoeg kennis van modbus om te weten wat dit is. Wel
vreemd dat het lijkt of er specifiek 1 adres niet goed werkt. Werkt je SWW
verder wel en kun je de temperatuur wel op het schermpje zien?

**Comment by PvdGulik** [comment]
Het bleek toch de SWW sensor waarin iets was verandert.... weet nog niet hoe, door een update?
Iig werkt het weer.
