### ISSUE TITLE
Anti-pendel koelen

### ISSUE THREAD

**Issue by overlordt** [altrnate32/esp-lg-control#11]
Werkt esp-lg-control ook om pendel gedrag tegen te gaan bij het koelen?

Mijn LG loopt snel op in RPM en stopt kort daarna met koelen omdat de minimale (condens) temperatuur bereikt is.

**Comment by altrnate32** [comment]
Nee er zit geen ondersteuning in voor koelen. Maar dat is relatief
eenvoudig in te bouwen als je hem forkt. Of het vervolgens ook echt werkt
is natuurlijk de vraag.
