### ISSUE TITLE
Silent Mode Toggle not working, Feature Request "SG Ready" Energy State Selector

### ISSUE THREAD

**Issue by fabaklava** [altrnate32/esp-lg-control#12]
Hi altrnate 32,

Thank you for the great work! Is the Silent Mode function hardcoded in your script? I'm unable to deactivate it in HASS, and since it keeps reverting every time, I wanted to ask whether that's a bug or a energy saving feature. 

I also wondered if you would consider adding the "SG Ready" energy state selection in a future update. 

Best,
F

**Comment by altrnate32** [comment]
Hi, there are two settings temperature for silent always on and temperature
for silent always off. This switches silent mode on based on
outside temperature. Silent mode on really helps to prevent overshooting
and helps create a more stable run. But below a certain temperature it
causes more defrosts and less performance.

If you want it always on or off just adjust the mentioned temperatures (if
you want it always off set temperature for silent always on and silent
always off at the max allowed.)

**Comment by fabaklava** [comment]
Got it, thanks for the quick reply.
