### ISSUE TITLE
Do I need Pi485 module?

### ISSUE THREAD

**Issue by martiinezz** [altrnate32/esp-lg-control#13]
I have older 16 kW rated Therma V pump and pi485 slot in external unit is empty. My understanding is that I need to buy pi485 module first to be able to do integration?

**Comment by altrnate32** [comment]
Hi,

You need a modbus interface on the LG. I don't know if the pi485 is the
only modbus interface available. My machine seems to have it integrated on
the board and not in a separate module. Maybe check the correct version of
your manual?

**Comment by martiinezz** [comment]
Will do thanks :)
