### ISSUE TITLE
Add on-off button

### ISSUE THREAD

**Issue by PvdGulik** [altrnate32/esp-lg-control#14]
As discussed on Tweakers, please add a button to enable/disabele the control part of the script.
This so you can use the Ai of the RMC as alternative.
Please keep the sensorpart of the script working.

Thanks!

**Comment by altrnate32** [comment]
Added in commit 157bf61adef8b83a83aad74839d9267285e147da
Please test

**Comment by PvdGulik** [comment]
Thanks,

Installed, will test this week!
