### ISSUE TITLE
Change flow to actual value

### ISSUE THREAD

**Issue by PvdGulik** [altrnate32/esp-lg-control#16]
To see the actual flow in all cases the pump is running please follwing code in file "lg-heatpump-modbus.yaml"

`  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 8
    unit_of_measurement: "L/m"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: |-
      if(x > 5) return x;
      else return 0.0;
    icon: mdi:waves-arrow-right`

to 

`- platform: modbus_controller
    modbus_controller_id: lg
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 8
    unit_of_measurement: "l/min"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: |-
     if (id(pump_running).state) return x;
      else return 0.0;
    icon: mdi:waves-arrow-right`

Thanks!

**Comment by altrnate32** [comment]
My pump reports 0 flow as 5 ltr/m, so this makes sure that 0 is reported for actual 0 flow instead of 5. Feel free to fork and ajust in your own private fork.
