### ISSUE TITLE
Add few unknown registers

### ISSUE THREAD

**Issue by PvdGulik** [altrnate32/esp-lg-control#17]
Please change code to change unknown to know registers:

Old code:

`- platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 16"
    id: temp16
    register_type: read
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown register 17"
    id: temp17
    register_type: read
    address: 17
    value_type: S_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 18"
    id: temp18
    register_type: read
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 19"
    id: temp19
    register_type: read
    address: 19
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 0.1    
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Condenser Temp"
    id: condensor_temp
    register_type: read
    address: 20
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:hvac
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Value 22"
    id: unknown22
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "W"
    icon: mdi:meter-electric-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pressure 2"
    id: temp23
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 2
    unit_of_measurement: "bar"
    filters:
      - multiply: 0.01`

New code:
` - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pipe in Temp"
    id: temp16
    register_type: read
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pipe Out Temp"
    id: temp17
    register_type: read
    address: 17
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Suction Temp"
    id: temp18
    register_type: read
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Fan RPM"
    id: temp19
    register_type: read
    address: 19
    unit_of_measurement: "rpm"
    value_type: S_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Condenser Temp"
    id: condensor_temp
    register_type: read
    address: 20
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:hvac
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "High Press"
    id: high_press
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"
    icon: mdi:meter-electric-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Low Press"
    id: low_press
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"`

Thanks!

**Comment by altrnate32** [comment]
Are you using the correct version? I do not see your 'Old code' in lg-heatpump-control/sensors/lg-heatpump-modbus.yaml

**Comment by PvdGulik** [comment]
You already used the new registers. I used not the most recent code, sorry ;-)
