### ISSUE TITLE
WP Sensed Power

### ISSUE THREAD

**Issue by melwinek** [altrnate32/esp-lg-control#2]
register_type: read
    address: 22

Is it for sure Sensed Power?
I have an electric meter connected and the results are totally different.

In attachment blue color is from electric meter.

![image](https://user-images.githubusercontent.com/10649327/208871809-28a09572-d275-4076-aa91-5483f31c687d.png)

**Comment by altrnate32** [comment]
Hi,

Unfortunately I have noticed that the modbus registers are a bit of a
lottery. Depending on firmware version and sometimes even vary between
countries. On my setup it is pretty congruent with an external powermeter,
but I cannot guarantee the same for you.

**Comment by altrnate32** [comment]
Refer to #5

**Comment by altrnate32** [comment]
Opened separate issue

**Comment by altrnate32** [comment]
Opened separate issue
