### ISSUE TITLE
Failed when uploading the latest config to esp32 board

### ISSUE THREAD

**Issue by Scar172** [altrnate32/esp-lg-control#22]
When validating the config it seems correct, however after uploading it to the board i get an error / failed.
Seems to be an issue with the the following line? Any idea's?

https://github.com/altrnate32/esp-lg-control/blob/ee6adb194b5e6578d267893d50bc08b1bb733317/lg-heatpump-control/lg-heatpump-state-machine.h#L620

Compiling .pioenvs/..../src/main.cpp.o
/config/esphome/lg-heatpump-control/lg-heatpump-state-machine.yaml: In lambda function:
/config/esphome/lg-heatpump-control/lg-heatpump-state-machine.yaml:183:49: error: invalid types 'int[input_types]' for array subscript
         if(new_target != INPUT[TEMP_NEW_TARGET]->value){
                                                 ^

<img width="672" alt="image" src="https://github.com/user-attachments/assets/c3340434-183f-424e-ae24-2bff1f96ba24">

**Comment by altrnate32** [comment]
Thanks for reporting! Found the error, it was a different line in the .yaml and not in the .h file. Is fixed in main branch.
