### ISSUE TITLE
PUMP A2

### ISSUE THREAD

**Issue by Pioszym** [altrnate32/esp-lg-control#7]
Hello. 
I have LG Therma V Split 7kW series 5. I use a floor heating buffer and an external pump connected to the PCB terminals "TB_EXT -> PUMP A2".
Does any modbus register indicate the "PUMP A2" status?

![image](https://user-images.githubusercontent.com/80012387/215962928-e4e9e416-572a-4f17-a19f-c28977efc617.png)

**Comment by Pioszym** [comment]
Found and added. Topic to be closed.

![image](https://user-images.githubusercontent.com/80012387/216561615-14e207f8-d14d-4bb5-b7b3-884020f1d72c.png)

**Comment by altrnate32** [comment]
good find, thanks for sharing
