### ISSUE TITLE
Explanation for calculation of startup target

### ISSUE THREAD

**Issue by georgeboot** [altrnate32/esp-lg-control#8]
Once again, thanks for your amazing work!

Can you please elaborate on the reasoning of the below code:

https://github.com/altrnate32/esp-lg-control/blob/d138c303eb8172647cc4d0e9c6580229efbd6fdb/lg-heatpump-control/lg-heatpump-state-machine.yaml#L110-L112

The first part makes sense: set the target to whatever the `STOOKLIJN_TARGET` is, minus a weather depended correction.

The second part seems odd to me. Why would you ever allow the target to be below the current tracking value? Isn't the whole point to get the compressor running?

Previously you took `TRACKING_VALUE` and added 2, maxed out at the `STOOKLIJN_TARGET`. Curious to hear what made you switch to this algo instead.

**Comment by altrnate32** [comment]
I was first on the same track as you, but then I thought: what do I actually want. Do I really want the compressor to start, or do I want water with the correct temperature? Forcing a compressor start generates unexpected behavior like a target of 50 degrees after a dhw run. In the end I get better results with accepting that the pump will not run the compressor if the water temp is higher then the set temp.

**Comment by altrnate32** [comment]
Sorry, I now see the confusion. I have recently changed this, but not committed. You are absolutely right, the mentioned code is incorrect and it introduces issues in target setting. I just pushed the fix.

**Comment by georgeboot** [comment]
Awesome, thanks a lot!
