### ISSUE TITLE
Thermostat switching

### ISSUE THREAD

**Issue by Toenou** [altrnate32/esp-lg-control#9]
Today the WP switched off on thermostat signal, all went well with the thermostat off and on delay. However after < 2 minutes in 'START' stage the thermostat signal went 'off' again. Roughly one minute later the compressor switched 'on' (thermostat still off). Controller state moved on to 'STARTING' for half a minute and continued to 'AFTERRUN'. One minute in 'AFTERRUN' the compressor switched off. 
This is not to what I would expect from happening. What I expected either is the compressor didn't start at all or would continue to run for much longer. As the time between thermostat switching off and compressor switching on is 1 min 14 sec, I guess this could have been caught by the state machine. 
After typing this story I realized I can add a picture :)
![image](https://user-images.githubusercontent.com/118055778/218835999-64123785-99ae-4549-9034-20b4365b7769.png)

Looked at the code, but I am still a newbie In C++, your code still is too advanced for me. So I couldn't determine whether this is according to what you intended or indeed is a bug, let alone defining the cause of it.

Bernard

**Comment by altrnate32** [comment]
Hi, during the start phase the thermostat input is not checked, but it is checked during ‘starting’. That may explain the behavior you are encountering. May I ask what your settings are for thermostat off delay and minimum run time?

**Comment by Toenou** [comment]
Hi, Thanks for the prompt reply. Thermostat_off delay is 12 minutes,
thermostat_on delay 14 minutes. I'm using a TADO controller that creates
PWM with a period time of 20 minutes.

**Comment by Toenou** [comment]
Clear, thanks for the explanation. Appreciate if it can be addressed in a
next update of the code

**Comment by Toenou** [comment]
Great, Thanks lot!!
Have the update running!

**Comment by altrnate32** [comment]
You are welcome!
